apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: event-management
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: stefantagarski/event-frontend:1.0
          ports:
            - containerPort: 8501
          env:
            - name: API_BASE_URL
              value: "http://backend-service:5000/api"
            - name: BACKEND_URL
              value: "http://backend-service:5000"