version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: event_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db  # Use named volume instead of bind mount
    networks:
      - event_network

  backend:
    # For development - use build
    build:
      context: ./backend
      dockerfile: Dockerfile
    # For production - CI/CD will replace this with image reference
    image: ${DOCKER_USERNAME}/event-backend:${IMAGE_TAG:-latest}
    container_name: event_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@event_mongodb:27017/${MONGO_DATABASE}?authSource=admin
      DATABASE_NAME: ${MONGO_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: production
    depends_on:
      - mongodb
    networks:
      - event_network
    # Remove volume mount for production
    # volumes:
    #   - ./backend:/app

  frontend:
    # For development - use build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # For production - CI/CD will replace this with image reference
    image: ${DOCKER_USERNAME}/event-frontend:${IMAGE_TAG:-latest}
    container_name: event_frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://event_backend:5000/api
    depends_on:
      - backend
    networks:
      - event_network
    # Remove volume mount for production
    # volumes:
    #   - ./frontend:/app

volumes:
  mongodb_data:

networks:
  event_network:
    driver: bridge