# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: event-management
  labels:
    app: event-management

---
# ConfigMap for Application
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: event-management
data:
  MONGO_DATABASE: "eventdb"
  FLASK_ENV: "production"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"

---
# Secret for Application
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: event-management
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_ROOT_PASSWORD: YWRtaW4=  # admin
  SECRET_KEY: bXlzZWNyZXRrZXk=  # mysecretkey

---
# Deployment for Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: event-management
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: backend
          image: stefantagarski/event-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_PORT
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DATABASE
            - name: MONGO_URI
              value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(MONGO_DATABASE)?authSource=admin"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEY
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FLASK_ENV
        - name: frontend
          image: stefantagarski/event-frontend:latest
          ports:
            - containerPort: 8501
          env:
            - name: API_BASE_URL
              value: "http://backend-service:5000/api"
            - name: BACKEND_URL
              value: "http://backend-service:5000"

---
# Service for Backend (Internal cluster communication)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: event-management
  labels:
    app: backend
spec:
  selector:
    app: app
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
# Service for Application (External access via LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: event-management
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: backend
      port: 5000
      targetPort: 5000
    - name: frontend
      port: 8501
      targetPort: 8501
  type: LoadBalancer

---
# Ingress for Application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: event-management
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: event-management.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 8501
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 5000

---
# Service for MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: event-management
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP

---
# ConfigMap for MongoDB
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: event-management
data:
  MONGO_INITDB_DATABASE: "eventdb"

---
# Secret for MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: event-management
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=  # admin

---
# StatefulSet for MongoDB
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: event-management
  labels:
    app: mongodb
spec:
  serviceName: "mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_INITDB_DATABASE
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi