# Secret for Application
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: event-management
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_ROOT_PASSWORD: YWRtaW4=  # admin
  SECRET_KEY: bXlzZWNyZXRrZXk=  # mysecretkey

---
# Secret for MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: event-management
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=  # admin